#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 22 20:03:40 2020

@author: stanley-yu
"""
def insertionSort(arr): 
    for i in range(1, len(arr)): 
        print(arr)
        copy = arr[i]
        j = i-1
        while j >= 0 and copy < arr[j]:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = copy
    print(arr)
    return arr
        
        
arr = [12, 11, 13, 5, 6] 
insertionSort(arr)

