#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 22 19:52:49 2020

@author: stanley-yu
"""

def insertionSort(arr): 
    for i in range(1, len(arr)): 
        print(arr)
        key = arr[i] 
        j = i - 1
        while j >= 0 and key < arr[j]: 
            arr[j+1] = arr[j] 
            j -= 1 
        arr[j+1] = key
   
    print(arr)         
    return arr

arr = [12, 11, 13, 5, 6] 
insertionSort(arr)